In [1]:
import pandas as pd
sales = pd.read_csv("Data/sales.csv")
sales

,State,Total Expenses,Product,Sales,Market Size,Profit,Market,Marketing,Product Type,Inventory,Type
0,California,63.0,Amaretto,109.0,Major Market,-131.0,West,40,Coffee,2947.0,Regular
1,California,55.0,Green Tea,201.0,Major Market,88.0,West,24,Tea,659.0,Regular
2,California,143.0,Caffe Mocha,289.0,Major Market,25.0,West,109,Espresso,788.0,Regular
3,California,113.0,Decaf Espresso,576.0,Major Market,216.0,West,81,Espresso,1744.0,Decaf
4,California,37.0,Chamomile,247.0,Major Market,148.0,West,26,Herbal Tea,809.0,Decaf
...,...,...,...,...,...,...,...,...,...,...,...
4236,Wisconsin,34.0,Darjeeling,90.0,Small Market,20.0,Central,11,Tea,458.0,Regular
4237,Wisconsin,36.0,Darjeeling,113.0,Small Market,31.0,Central,14,Tea,454.0,Regular
4238,Wisconsin,86.0,Earl Grey,150.0,Small Market,1.0,Central,57,Tea,506.0,Regular
4239,Wisconsin,79.0,Earl Grey,131.0,Small Market,-3.0,Central,49,Tea,627.0,Regular
4240,Wisconsin,87.0,Earl Grey,165.0,Small Market,4.0,Central,58,Tea,513.0,Regular

In [2]:
sales.sort_values(by="Sales") #sort by sales in ascending order

,State,Total Expenses,Product,Sales,Market Size,Profit,Market,Marketing,Product Type,Inventory,Type
1914,Nevada,126.0,Green Tea,17.0,Small Market,-354.0,West,93,Tea,1419.0,Regular
1923,Nevada,124.0,Green Tea,18.0,Small Market,-524.0,West,100,Tea,3742.0,Regular
1917,Nevada,133.0,Green Tea,18.0,Small Market,-380.0,West,100,Tea,3742.0,Regular
2036,Nevada,132.0,Green Tea,19.0,Small Market,-552.0,West,93,Tea,1419.0,Regular
2034,Nevada,147.0,Green Tea,19.0,Small Market,-430.0,West,114,Tea,6413.0,Regular
...,...,...,...,...,...,...,...,...,...,...,...
131,California,178.0,Columbian,910.0,Major Market,368.0,West,127,Coffee,2617.0,Regular
2644,New York,178.0,Columbian,912.0,Major Market,370.0,East,127,Coffee,2654.0,Regular
157,California,178.0,Columbian,912.0,Major Market,370.0,West,127,Coffee,2654.0,Regular
502,Colorado,54.0,Decaf Espresso,NaN,Major Market,80.0,Central,23,Espresso,541.0,Decaf
508,Colorado,71.0,Chamomile,NaN,Major Market,99.0,Central,47,Herbal Tea,1073.0,Decaf

In [5]:
sales.sort_values(by=["Sales",'Profit'], ascending=False)

,State,Total Expenses,Product,Sales,Market Size,Profit,Market,Marketing,Product Type,Inventory,Type
157,California,178.0,Columbian,912.0,Major Market,370.0,West,127,Coffee,2654.0,Regular
2644,New York,178.0,Columbian,912.0,Major Market,370.0,East,127,Coffee,2654.0,Regular
131,California,178.0,Columbian,910.0,Major Market,368.0,West,127,Coffee,2617.0,Regular
2645,New York,178.0,Columbian,910.0,Major Market,368.0,East,127,Coffee,2617.0,Regular
132,California,166.0,Columbian,904.0,Major Market,511.0,West,127,Coffee,2654.0,Regular
...,...,...,...,...,...,...,...,...,...,...,...
1917,Nevada,133.0,Green Tea,18.0,Small Market,-380.0,West,100,Tea,3742.0,Regular
1923,Nevada,124.0,Green Tea,18.0,Small Market,-524.0,West,100,Tea,3742.0,Regular
1914,Nevada,126.0,Green Tea,17.0,Small Market,-354.0,West,93,Tea,1419.0,Regular
508,Colorado,71.0,Chamomile,NaN,Major Market,99.0,Central,47,Herbal Tea,1073.0,Decaf
502,Colorado,54.0,Decaf Espresso,NaN,Major Market,80.0,Central,23,Espresso,541.0,Decaf

In [7]:
sales.sort_index(ascending=False)

,State,Total Expenses,Product,Sales,Market Size,Profit,Market,Marketing,Product Type,Inventory,Type
4240,Wisconsin,87.0,Earl Grey,165.0,Small Market,4.0,Central,58,Tea,513.0,Regular
4239,Wisconsin,79.0,Earl Grey,131.0,Small Market,-3.0,Central,49,Tea,627.0,Regular
4238,Wisconsin,86.0,Earl Grey,150.0,Small Market,1.0,Central,57,Tea,506.0,Regular
4237,Wisconsin,36.0,Darjeeling,113.0,Small Market,31.0,Central,14,Tea,454.0,Regular
4236,Wisconsin,34.0,Darjeeling,90.0,Small Market,20.0,Central,11,Tea,458.0,Regular
...,...,...,...,...,...,...,...,...,...,...,...
4,California,37.0,Chamomile,247.0,Major Market,148.0,West,26,Herbal Tea,809.0,Decaf
3,California,113.0,Decaf Espresso,576.0,Major Market,216.0,West,81,Espresso,1744.0,Decaf
2,California,143.0,Caffe Mocha,289.0,Major Market,25.0,West,109,Espresso,788.0,Regular
1,California,55.0,Green Tea,201.0,Major Market,88.0,West,24,Tea,659.0,Regular
0,California,63.0,Amaretto,109.0,Major Market,-131.0,West,40,Coffee,2947.0,Regular

In [10]:
sales['Marketing'].sort_values() #can also use the dot notation of sales.marketing.sort_values()

2145      0
2203      0
2204      0
2205      0
2206      0
       ...
2549    156
271     156
77      156
2494    156
1948    156
Name: Marketing, Length: 4241, dtype: int64